export const SRI_LANKAN_DISTRICTS = [
  { name: 'Colombo', zone: 'WL1', province: 'Western' },
  { name: 'Gampaha', zone: 'WL1', province: 'Western' },
  { name: 'Kalutara', zone: 'WL2', province: 'Western' },
  { name: 'Kandy', zone: 'WM1', province: 'Central' },
  { name: 'Matale', zone: 'WM2', province: 'Central' },
  { name: 'Nuwara Eliya', zone: 'WU1', province: 'Central' },
  { name: 'Galle', zone: 'WL3', province: 'Southern' },
  { name: 'Matara', zone: 'WL3', province: 'Southern' },
  { name: 'Hambantota', zone: 'DL1', province: 'Southern' },
  { name: 'Jaffna', zone: 'DL2', province: 'Northern' },
  { name: 'Kilinochchi', zone: 'DL2', province: 'Northern' },
  { name: 'Mannar', zone: 'DL2', province: 'Northern' },
  { name: 'Vavuniya', zone: 'DL3', province: 'Northern' },
  { name: 'Mullaitivu', zone: 'DL2', province: 'Northern' },
  { name: 'Batticaloa', zone: 'DL1', province: 'Eastern' },
  { name: 'Ampara', zone: 'DL1', province: 'Eastern' },
  { name: 'Trincomalee', zone: 'DL1', province: 'Eastern' },
  { name: 'Kurunegala', zone: 'WM3', province: 'North Western' },
  { name: 'Puttalam', zone: 'DL1', province: 'North Western' },
  { name: 'Anuradhapura', zone: 'DL1', province: 'North Central' },
  { name: 'Polonnaruwa', zone: 'DL1', province: 'North Central' },
  { name: 'Badulla', zone: 'WM2', province: 'Uva' },
  { name: 'Moneragala', zone: 'DL3', province: 'Uva' },
  { name: 'Ratnapura', zone: 'WM3', province: 'Sabaragamuwa' },
  { name: 'Kegalle', zone: 'WM2', province: 'Sabaragamuwa' },
]

export const ZONE_DESCRIPTIONS: Record<string, string> = {
  WL1: 'Wet Zone Low Country 1',
  WL2: 'Wet Zone Low Country 2',
  WL3: 'Wet Zone Low Country 3',
  WM1: 'Wet Zone Mid Country 1',
  WM2: 'Wet Zone Mid Country 2',
  WM3: 'Wet Zone Mid Country 3',
  WU1: 'Wet Zone Up Country 1',
  DL1: 'Dry Zone Low Country 1',
  DL2: 'Dry Zone Low Country 2',
  DL3: 'Dry Zone Low Country 3',
}
